services:
  - type: web
    name: election-backend
    env: python
    region: london
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
