services:
  - type: web
    name: election-predictor-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: CORS_ORIGINS
        value: "http://localhost:5173,https://your-frontend.onrender.com"
