import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useNavigate } from "react-router-dom";
import { MapPin, Compass, Vote, Edit, RefreshCw, UserCircle } from "lucide-react";
import { partyColors, partyLabels } from "@/utils/partyMap";
const ProfileCard = ({ user, lastPrediction }) => {
    const navigate = useNavigate();
    return (_jsxs("div", { className: "p-6 bg-white dark:bg-slate-800 rounded-2xl shadow-md flex flex-col items-center space-y-5", children: [_jsx("h2", { className: "text-lg font-bold text-gray-700 dark:text-gray-200", children: "Your Profile" }), user.profilePicUrl ? (_jsx("img", { src: user.profilePicUrl, alt: "Profile", className: "w-20 h-20 rounded-full object-cover shadow-md border-2 border-gray-200 dark:border-slate-700" })) : (_jsx(UserCircle, { className: "w-20 h-20 text-gray-400 dark:text-gray-500" })), _jsxs("div", { className: "text-center", children: [_jsx("h3", { className: "text-lg font-semibold dark:text-white", children: user.displayName || user.username || "Anonymous User" }), _jsx("p", { className: "text-sm text-gray-500 dark:text-gray-400", children: user.email || "No email available" })] }), _jsxs("div", { className: "w-full space-y-2 text-sm", children: [user.region && (_jsxs("p", { className: "flex items-center justify-between text-gray-600 dark:text-gray-300", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(MapPin, { size: 16 }), " Region:"] }), _jsx("span", { children: user.region })] })), user.chosenAlignment && (_jsxs("p", { className: "flex items-center justify-between text-gray-600 dark:text-gray-300", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(Compass, { size: 16 }), " Alignment:"] }), _jsx("span", { children: partyLabels[user.chosenAlignment] })] })), lastPrediction && (_jsxs("p", { className: "flex items-center justify-between text-gray-600 dark:text-gray-300", children: [_jsxs("span", { className: "flex items-center gap-2", children: [_jsx(Vote, { size: 16 }), " Predicted:"] }), _jsx("span", { className: "px-2 py-1 rounded-md text-white text-xs font-medium", style: {
                                    backgroundColor: partyColors[lastPrediction.party] || "#6B7280",
                                }, children: lastPrediction.partyLabel || lastPrediction.party })] }))] }), _jsxs("div", { className: "flex flex-col sm:flex-row gap-3 mt-4 w-full", children: [_jsxs("button", { onClick: () => navigate("/survey"), className: "flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition", children: [_jsx(RefreshCw, { size: 16 }), " Retake Survey"] }), _jsxs("button", { onClick: () => navigate("/settings"), className: "flex-1 flex items-center justify-center gap-2 px-4 py-2 bg-gray-200 dark:bg-slate-700 dark:text-white rounded-lg hover:bg-gray-300 dark:hover:bg-slate-600 transition", children: [_jsx(Edit, { size: 16 }), " Edit Profile"] })] })] }));
};
export default ProfileCard;
