// src/utils/partyLogic.ts

export type Party =
  | "lab"
  | "con"
  | "ld"
  | "green"
  | "reform"
  | "snp"
  | "other";

export const partyLogic: Record<Party, Record<string, string[]>> = {
  lab: {
    age_bracket: ["18–24", "25–34", "35–44"],
    education_level: ["bachelors degree"],
    household_income: ["£20,000–£40,000"],
    socioeconomic_class: ["working class"],
    housing_status: ["living with family", "council housing", "renter"],
    constituency_leaning: ["labour"],
    vote_national: ["yes", "no"],
    vote_local: ["yes", "no"],
    satisfaction_national_government: ["dissatisfied", "very dissatisfied"],
    importance_economy: ["very important"],
    importance_social_issues: ["very important"],
    support_welfare_spending: ["yes"],
    tax_on_wealthy: ["yes"],
    trust_mainstream_media: ["low", "neutral"],
    concern_political_corruption: ["somewhat concerned"],
    climate_priority: ["yes"],
    immigration_policy_stance: ["more open"],
    trust_public_institutions: ["low"],
    region_boost: ["north of england", "wales", "london"],
  },

  con: {
    age_bracket: ["35–44", "45–54", "55–64", "65+"],
    education_level: ["masters degree", "phd or higher"],
    household_income: ["£60,000-£80,000", "£80,000 +"],
    socioeconomic_class: ["upper middle class"],
    housing_status: ["homeowner"],
    constituency_leaning: ["conservative"],
    vote_national: ["yes"],
    vote_local: ["yes"],
    satisfaction_national_government: ["dissatisfied"],
    importance_economy: ["not important"],
    importance_social_issues: ["not important"],
    support_welfare_spending: ["no"],
    tax_on_wealthy: ["no"],
    trust_mainstream_media: ["high", "very high"],
    concern_political_corruption: ["not concerned"],
    climate_priority: ["no"],
    immigration_policy_stance: ["restrictive", "very restrictive"],
    trust_public_institutions: ["high", "very high"],
    region_boost: ["south of england"],
  },

  ld: {
    age_bracket: ["35–44", "45–54"],
    education_level: ["masters degree", "phd or higher"],
    household_income: ["£40,000–£60,000", "£60,000-£80,000"],
    socioeconomic_class: ["middle class"],
    housing_status: ["renter", "homeowner"],
    constituency_leaning: ["liberal democrat"],
    vote_national: ["yes"],
    vote_local: ["yes"],
    satisfaction_national_government: ["neutral"],
    importance_economy: ["somewhat important"],
    importance_social_issues: ["somewhat important"],
    support_welfare_spending: ["yes"],
    tax_on_wealthy: ["yes", "no"],
    trust_mainstream_media: ["medium"],
    concern_political_corruption: ["somewhat concerned"],
    climate_priority: ["yes"],
    immigration_policy_stance: ["more open", "unbothered"],
    trust_public_institutions: ["medium"],
    region_boost: ["london", "north of england"],
  },

  green: {
    age_bracket: ["18–24", "25–34"],
    education_level: ["bachelors degree", "masters degree"],
    household_income: ["under £20,000", "£20,000–£40,000"],
    socioeconomic_class: ["working class", "lower middle class"],
    housing_status: ["renter", "living with family", "council housing"],
    constituency_leaning: ["green"],
    vote_national: ["yes", "no"],
    vote_local: ["no"],
    satisfaction_national_government: ["very dissatisfied"],
    importance_economy: ["important"],
    importance_social_issues: ["important"],
    support_welfare_spending: ["yes"],
    tax_on_wealthy: ["yes"],
    trust_mainstream_media: ["very low"],
    concern_political_corruption: ["very concerned"],
    climate_priority: ["yes"],
    immigration_policy_stance: ["more open"],
    trust_public_institutions: ["very low"],
    region_boost: ["london"],
  },

  reform: {
    age_bracket: ["35–44", "45–54", "55–64"],
    education_level: ["no qualification", "gcse or equivalent", "a-level or equivalent"],
    household_income: ["under £20,000"],
    socioeconomic_class: ["working class"],
    housing_status: ["council housing", "living with family"],
    constituency_leaning: ["conservative", "reform"],
    vote_national: ["no"],
    vote_local: ["no"],
    satisfaction_national_government: ["very dissatisfied"],
    importance_economy: ["important"],
    importance_social_issues: ["not important"],
    support_welfare_spending: ["no"],
    tax_on_wealthy: ["no"],
    trust_mainstream_media: ["very high"],
    concern_political_corruption: ["very concerned"],
    climate_priority: ["no"],
    immigration_policy_stance: ["very restrictive"],
    trust_public_institutions: ["very high"],
    region_boost: ["midlands", "north of england", "south of england"],
  },

  snp: {
    age_bracket: ["25–34", "35–44", "45–54"],
    education_level: ["bachelors degree", "gcse or equivalent"],
    household_income: ["£20,000–£40,000", "£40,000–£60,000"],
    socioeconomic_class: ["working class", "middle class"],
    housing_status: ["renter", "homeowner"],
    constituency_leaning: ["snp"],
    vote_national: ["yes"],
    vote_local: ["yes"],
    satisfaction_national_government: ["dissatisfied"],
    importance_economy: ["important"],
    importance_social_issues: ["very important"],
    support_welfare_spending: ["yes"],
    tax_on_wealthy: ["yes"],
    trust_mainstream_media: ["neutral"],
    concern_political_corruption: ["somewhat concerned"],
    climate_priority: ["yes"],
    immigration_policy_stance: ["more open"],
    trust_public_institutions: ["medium"],
    region_boost: ["scotland"],
  },

  other: {
    constituency_leaning: ["other"],
    vote_national: ["no"],
    vote_local: ["no"],
    region_boost: ["wales", "northern ireland"],
  },
};
