// partyLogic.ts

export type Party =
  | "Labour"
  | "Conservative"
  | "Liberal Democrats"
  | "Green"
  | "Reform"
  | "SNP"
  | "Plaid Cymru"
  | "Sinn Féin";

export const partyLogic: Record<Party, Record<string, string[]>> = {
  Labour: {
    age_bracket: ["18–24", "25–34"],
    education_level: ["GCSE or equivalent", "Bachelor’s degree", "Master’s degree"],
    household_income: ["Under £20,000", "£20,000–£40,000"],
    socioeconomic_class: ["Working class", "Lower-middle class"],
    housing_status: ["Renting", "Living with family"],
    constituency_leaning: ["Strongly Labour", "Leaning Labour"],
    vote_national: ["Always", "Often"],
    vote_local: ["Always", "Often"],
    satisfaction_national_government: ["Very dissatisfied", "Dissatisfied"],
    importance_economy: ["Very important", "Important"],
    importance_social_issues: ["Very important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes"],
    trust_mainstream_media: ["Some", "Neutral"],
    concern_political_corruption: ["Very concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Some", "Neutral"]
  },
  Conservative: {
    age_bracket: ["55–64", "65+"],
    education_level: ["No qualification", "GCSE or equivalent"],
    household_income: ["£60,000–£80,000", "£80,000–£100,000", "Over £100,000"],
    socioeconomic_class: ["Upper-middle class", "Upper class"],
    housing_status: ["Own outright", "Mortgage"],
    constituency_leaning: ["Strongly Conservative", "Leaning Conservative"],
    vote_national: ["Always"],
    vote_local: ["Always"],
    satisfaction_national_government: ["Very satisfied", "Satisfied"],
    importance_economy: ["Very important"],
    importance_social_issues: ["Important", "Somewhat important"],
    support_welfare_spending: ["No"],
    tax_on_wealthy: ["No"],
    trust_mainstream_media: ["A great deal"],
    concern_political_corruption: ["Not very concerned"],
    climate_priority: ["No"],
    immigration_policy_stance: ["More restrictive"],
    trust_public_institutions: ["A great deal"]
  },
  "Liberal Democrats": {
    age_bracket: ["25–34", "35–44", "45–54"],
    education_level: ["Bachelor’s degree", "Master’s degree", "PhD or higher"],
    household_income: ["£40,000–£60,000", "£60,000–£80,000"],
    socioeconomic_class: ["Middle class", "Upper-middle class"],
    housing_status: ["Mortgage", "Renting"],
    constituency_leaning: ["Strongly Liberal Democrat", "Leaning Liberal Democrat"],
    vote_national: ["Always", "Often"],
    vote_local: ["Always", "Often"],
    satisfaction_national_government: ["Dissatisfied", "Neutral"],
    importance_economy: ["Important", "Somewhat important"],
    importance_social_issues: ["Very important", "Important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes", "Unsure"],
    trust_mainstream_media: ["Some", "Neutral"],
    concern_political_corruption: ["Somewhat concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Some", "Neutral"]
  },
  Green: {
    age_bracket: ["18–24", "25–34"],
    education_level: ["Bachelor’s degree", "Master’s degree", "PhD or higher"],
    household_income: ["Under £20,000", "£20,000–£40,000"],
    socioeconomic_class: ["Lower-middle class", "Middle class"],
    housing_status: ["Renting"],
    constituency_leaning: ["Strongly Green", "Leaning Green"],
    vote_national: ["Often", "Sometimes"],
    vote_local: ["Always", "Often"],
    satisfaction_national_government: ["Very dissatisfied"],
    importance_economy: ["Important"],
    importance_social_issues: ["Very important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes"],
    trust_mainstream_media: ["Little", "None"],
    concern_political_corruption: ["Very concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Some"]
  },
  Reform: {
    age_bracket: ["45–54", "55–64", "65+"],
    education_level: ["No qualification", "GCSE or equivalent"],
    household_income: ["Under £20,000", "£20,000–£40,000", "£40,000–£60,000"],
    socioeconomic_class: ["Working class", "Lower-middle class"],
    housing_status: ["Mortgage", "Own outright"],
    constituency_leaning: ["Strongly Reform UK", "Leaning Reform UK"],
    vote_national: ["Always", "Often"],
    vote_local: ["Sometimes", "Rarely"],
    satisfaction_national_government: ["Very dissatisfied"],
    importance_economy: ["Very important"],
    importance_social_issues: ["Not very important"],
    support_welfare_spending: ["No"],
    tax_on_wealthy: ["No"],
    trust_mainstream_media: ["None", "Little"],
    concern_political_corruption: ["Very concerned"],
    climate_priority: ["No"],
    immigration_policy_stance: ["More restrictive"],
    trust_public_institutions: ["None", "Little"]
  },
  SNP: {
    age_bracket: ["25–34", "35–44", "45–54"],
    education_level: ["Bachelor’s degree", "GCSE or equivalent"],
    household_income: ["£20,000–£40,000", "£40,000–£60,000"],
    socioeconomic_class: ["Working class", "Middle class"],
    housing_status: ["Renting", "Mortgage"],
    constituency_leaning: ["Strongly SNP", "Leaning SNP"],
    vote_national: ["Always", "Often"],
    vote_local: ["Always", "Often"],
    satisfaction_national_government: ["Dissatisfied"],
    importance_economy: ["Important"],
    importance_social_issues: ["Very important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes"],
    trust_mainstream_media: ["Neutral", "Little"],
    concern_political_corruption: ["Somewhat concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Some"]
  },
  "Plaid Cymru": {
    age_bracket: ["35–44", "45–54"],
    education_level: ["GCSE or equivalent", "Bachelor’s degree"],
    household_income: ["£20,000–£40,000"],
    socioeconomic_class: ["Working class"],
    housing_status: ["Renting"],
    constituency_leaning: ["Strongly Plaid Cymru", "Leaning Plaid Cymru"],
    vote_national: ["Always", "Often"],
    vote_local: ["Often", "Sometimes"],
    satisfaction_national_government: ["Dissatisfied"],
    importance_economy: ["Important"],
    importance_social_issues: ["Important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes"],
    trust_mainstream_media: ["Neutral", "Little"],
    concern_political_corruption: ["Somewhat concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Some"]
  },
  "Sinn Féin": {
    age_bracket: ["18–24", "25–34"],
    education_level: ["GCSE or equivalent", "Bachelor’s degree"],
    household_income: ["Under £20,000"],
    socioeconomic_class: ["Working class"],
    housing_status: ["Renting"],
    constituency_leaning: ["Strongly Sinn Féin", "Leaning Sinn Féin"],
    vote_national: ["Always"],
    vote_local: ["Always"],
    satisfaction_national_government: ["Very dissatisfied"],
    importance_economy: ["Important"],
    importance_social_issues: ["Very important"],
    support_welfare_spending: ["Yes"],
    tax_on_wealthy: ["Yes"],
    trust_mainstream_media: ["None", "Little"],
    concern_political_corruption: ["Very concerned"],
    climate_priority: ["Yes"],
    immigration_policy_stance: ["More open"],
    trust_public_institutions: ["Little"]
  }
};
