// src/utils/regionalData.ts
export const regionalVoteShare = {
    Scotland: {
        lab: 38,
        con: 12,
        ld: 5,
        green: 4,
        snp: 30,
        reform: 7,
        other: 4,
    },
    Wales: {
        lab: 30,
        con: 12,
        ld: 6,
        green: 5,
        snp: 0,
        reform: 25,
        other: 22,
    },
    "North of England": {
        lab: 22,
        con: 10,
        ld: 8,
        green: 7,
        snp: 0,
        reform: 35,
        other: 18,
    },
    Midlands: {
        lab: 20,
        con: 8,
        ld: 8,
        green: 6,
        snp: 0,
        reform: 38,
        other: 20,
    },
    London: {
        lab: 35,
        con: 15,
        ld: 12,
        green: 10,
        snp: 0,
        reform: 8,
        other: 20,
    },
    "South of England": {
        lab: 25,
        con: 12,
        ld: 18,
        green: 8,
        snp: 0,
        reform: 25,
        other: 12,
    },
};
